config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  resources :roles
  get '/' => 'home#index', as: :root_path

  resources :severity_levels
  resources :incident_types
  resources :fires
  resources :incidents
  devise_for :users, controllers: { registrations: 'registrations' }
end

app/models/severity_level.rb
# frozen_string_literal: true
# :nodoc:
class SeverityLevel
  include NoBrainer::Document
  include NoBrainer::Document::Timestamps

  validates :name, :color, presence: true
  validates :color, color: true

  field :name, type: String
  field :color, type: String

  paginates_per 20

  has_many :fires, dependent: :nullify
end

app/controllers/severity_levels_controller.rb
# frozen_string_literal: true
# :nodoc:
class SeverityLevelsController < ApplicationController
  before_action :set_severity_level, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :master?, only: [:destroy]

  # GET /severity_levels
  # GET /severity_levels.json
  def index
    @severity_levels = SeverityLevel.order(:created_at).page params[:page]
  end

  # GET /severity_levels/1
  # GET /severity_levels/1.json
  def show
    @fires = Kaminari.paginate_array(@severity_level.fires).page(params[:page]).per(20)
  end

  # GET /severity_levels/new
  def new
    @severity_level = SeverityLevel.new
  end

  # GET /severity_levels/1/edit
  def edit
  end

  # POST /severity_levels
  # POST /severity_levels.json
  def create
    @severity_level = SeverityLevel.new(severity_level_params)

    respond_to do |format|
      if @severity_level.save
        format.html do
          redirect_to @severity_level,
                      notice: 'Severity level was successfully created.'
        end
        format.json { render :show, status: :created, location: @severity_level }
      else
        format.html { render :new }
        format.json { render json: @severity_level.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /severity_levels/1
  # PATCH/PUT /severity_levels/1.json
  def update
    respond_to do |format|
      if @severity_level.update(severity_level_params)
        format.html do
          redirect_to @severity_level,
                      notice: 'Severity level was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @severity_level }
      else
        format.html { render :edit }
        format.json { render json: @severity_level.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /severity_levels/1
  # DELETE /severity_levels/1.json
  def destroy
    @severity_level.destroy
    respond_to do |format|
      format.html do
        redirect_to severity_levels_url,
                    notice: 'Severity level was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_severity_level
    @severity_level = SeverityLevel.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def severity_level_params
    params.require(:severity_level).permit(:name, :color)
  end

  def master?
    return false unless current_user
    current_user.role.name.downcase.equal? 'master'
  end
end

app/helpers/severity_levels_helper.rb
# frozen_string_literal: true
# :nodoc:
module SeverityLevelsHelper
  # Render a span label for the given severity
  def severity_label(severity)
    text_color = text_color_for_bg(severity.color)
    "<span class='label' style='background: #{severity.color} ; color: #{text_color}'>
    #{severity.name}</span>".html_safe
  end

  # Find a sutiable color based on the background color
  def text_color_for_bg(bg_color)
    if bg_color.length == 4
      r, g, b = bg_color[1, 4].scan(/./).map { |v| (v * 2).hex }
    else
      r, g, b = bg_color[1, 7].scan(/.{2}/).map(&:hex)
    end

    if r && g && b
      decide_color r, g, b
    else
      '#FFFFFF'
    end
  end
end

def decide_color(r, g, b)
  if (r + g + b) > 500
    '#333333'
  else
    '#FFFFFF'
  end
end

app/views/severity_levels/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 spaced">
    <%= form_for(@severity_level) do |f| %>
    <% if @severity_level.errors.any? %>
    <div id="error_explanation">
      <p class="text-center text-danger"><%= pluralize(@severity_level.errors.count, "error") %> prohibited this level from being saved</p>
    </div>
    <% end %>

      <div class="row">
        <div class="col-md-8">
          <div class="form-group <%= @severity_level.errors[:name].empty? ? '' : 'has-error' %>">
            <%= f.label :name, class: 'control-label' %>
            <%= f.text_field :name, class: 'form-control' %>
            <% if not @severity_level.errors[:name].empty? %>
              <% @severity_level.errors[:name].each do |message| %>
              <span class="help-block"><%= message.capitalize %></span>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="col-md-4">
          <div class="form-group <%= @severity_level.errors[:color].empty? ? '' : 'has-error' %>">
            <%= f.label :color, class: 'control-label' %>
            <%= f.color_field :color, class: 'form-control' %>
            <% if not @severity_level.errors[:color].empty? %>
              <% @severity_level.errors[:color].each do |message| %>
              <span class="help-block"><%= message.capitalize %></span>
              <% end %>
            <% end %>
          </div>
        </div>
        </div>

      <div class="actions">
        <%= f.submit 'Save', class: ['btn', 'btn-success'] %>
      </div>
      <% end %>
    </div>
  </div>

app/views/severity_levels/edit.html.erb
<div class="container">
  <spaced>
    <div class="row">
      <div class="col-md-12">
        <div class="pull-left">
          <%= link_to icon('chevron-left', 'Back', class: 'fa-fw'), severity_levels_path %>
        </div>
        <div class="pull-right">
            <%= link_to icon('eye', 'Show', class: 'fa-fw'), @severity_level %> 
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <h1 class="text-center">Editing Severity Level</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <%= render 'layouts/notice', notice: notice %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <%= render 'form' %>
      </div>
    </div>
  </spaced>
</div>

app/views/severity_levels/index.html.erb
<div class="container spaced">
  <div class="row">
    <div class="col-sm-12">
      <div class="pull-right">
        <% if current_user %>
        <%= link_to icon('plus', 'New Level', class: 'fa-fw'), new_severity_level_path %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <h1 class="text-center">Listing Severity Levels</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <%= render 'layouts/notice', notice: notice %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <% if @severity_levels.empty? %>
      <p class="text-muted text-center lead">No levels added yet.</p>
      <% else %>
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Levels</th>
              <th colspan="4"></th>
            </tr>
          </thead>
          <tbody>
            <% @severity_levels.each do |severity_level| %>
            <tr>
              <td><%= severity_label severity_level %></td>
              <td><%= link_to icon('eye'), severity_level, class: 'text-info' %></td>
              <% if current_user %>
              <td><%= link_to icon('pencil'), edit_severity_level_path(severity_level), class: 'text-muted' %></td>
              <td><%= link_to icon('times'), severity_level, method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-danger' %></td>
              <% end %>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= paginate @severity_levels %>
    </div>
  </div>
</div>

app/views/severity_levels/new.html.erb
<div class="container">
  <spaced>
    <div class="row">
      <div class="col-md-12">
        <div class="pull-left">
          <%= link_to icon('chevron-left', 'Back', class: 'fa-fw'), severity_levels_path %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <h1 class="text-center">New Severity Level</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <%= render 'layouts/notice', notice: notice %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <%= render 'form' %>
      </div>
    </div>
  </spaced>
</div>

app/views/severity_levels/show.html.erb
<div class="container spaced">
  <div class="row">
    <div class="col-md-12">
      <div class="pull-left">
        <%= link_to icon('chevron-left', 'Back', class: 'fa-fw'), severity_levels_path %>
      </div>
      <div class="pull-right">
        <% if current_user %>
        <%= link_to icon('pencil', 'Edit this level', class: 'fa-fw'), edit_severity_level_path(@severity_level) %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <h1 class="text-center"><%= @severity_level.name %>&nbsp; severity fires</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= render 'layouts/notice', notice: notice %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <% if @severity_level.fires.empty? %>
      <p class="text-muted lead text-center">No fires reported with this severity yet</p>
      <% else %>
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Name</th>
              <th>Location</th>
              <th>Reporter</th>
              <th>Is Extinguished</th>
              <th>Severity</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @fires.each do |fire| %>
            <tr>
              <td><%= fire.name %></td>
              <td><%= fire.location.latitude.to_s.concat(', ').concat(fire.location.longitude.to_s) %></td>
              <td><%= fire.user.name %></td>
              <td>
                <% if fire.is_extinguished %>
                <span class="text-success"><i class="fa fa-check"></i></span>
                <% else %>
                <span class="text-danger"><i class="fa fa-times"></i></span>
                <% end %>
              </td>
              <td><%= severity_label fire.severity_level %></td>
              <td><%= link_to icon('eye'), fire, class: 'text-info' %></td>
              <% if current_user %>
              <td><%= link_to icon('pencil'), edit_fire_path(fire), class: 'text-muted' %></td>
              <td><%= link_to icon('times'), fire, method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-danger' %></td>
              <% end %>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= paginate @fires %>
    </div>
  </div>
</div>