config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  resources :roles
  get '/' => 'home#index', as: :root_path

  resources :severity_levels
  resources :incident_types
  resources :fires
  resources :incidents
  devise_for :users, controllers: { registrations: 'registrations' }
end

app/controllers/incident_types_controller.rb
# frozen_string_literal: true
# Controller for incident types
class IncidentTypesController < ApplicationController
  before_action :set_incident_type, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :master?, only: [:destroy]

  # GET /incident_types
  # GET /incident_types.json
  def index
    @incident_types = IncidentType.order(:updated_at).page params[:page]
  end

  # GET /incident_types/1
  # GET /incident_types/1.json
  def show
    @incidents = Kaminari.paginate_array(@incident_type.incidents).page(params[:page]).per(20)
  end

  # GET /incident_types/new
  def new
    @incident_type = IncidentType.new
  end

  # GET /incident_types/1/edit
  def edit
  end

  # POST /incident_types
  # POST /incident_types.json
  def create
    @incident_type = IncidentType.new(incident_type_params)

    respond_to do |format|
      if @incident_type.save
        format.html do
          redirect_to @incident_type,
                      notice: 'Incident type was successfully created.'
        end
        format.json { render :show, status: :created, location: @incident_type }
      else
        format.html { render :new }
        format.json { render json: @incident_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incident_types/1
  # PATCH/PUT /incident_types/1.json
  def update
    respond_to do |format|
      if @incident_type.update(incident_type_params)
        format.html do
          redirect_to @incident_type,
                      notice: 'Incident type was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @incident_type }
      else
        format.html { render :edit }
        format.json { render json: @incident_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incident_types/1
  # DELETE /incident_types/1.json
  def destroy
    @incident_type.destroy
    respond_to do |format|
      format.html do
        redirect_to incident_types_url,
                    notice: 'Incident type was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_incident_type
    @incident_type = IncidentType.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def incident_type_params
    params.require(:incident_type).permit(:name)
  end

  def master?
    return false unless current_user
    current_user.role.name.downcase.equal? 'master'
  end
end

app/helpers/incident_types_helper.rb
# frozen_string_literal: true
# Incident Type Heper
module IncidentTypesHelper
end

app/views/incident_types/_form.html.erb
<div class="row">
  <div class="col-sm-12 col-md-4 col-md-offset-4 spaced">
    <%= form_for(@incident_type) do |f| %>
    <% if @incident_type.errors.any? %>
    <div id="error_explanation">
      <p class="text-danger text-center"><%= pluralize(@incident_type.errors.count, "error") %> prohibited this type from being saved</p>
    </div>
    <% end %>

    <div class="form-group <%= @incident_type.errors[:name].empty? ? '' : 'has-error' %>">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: 'form-control' %>
      <% if not @incident_type.errors[:name].empty? %>
        <% @incident_type.errors[:name].each do |message| %>
        <span class="help-block"><%= message.capitalize %></span>
        <% end %>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.submit 'Save', class: ['btn', 'btn-success'] %>
    </div>
    <% end %>

  </div>
</div>

app/views/incident_types/edit.html.erb
<div class="container spaced">
  <div class="row col-sm-12">
    <div class="pull-left">
      <%= link_to icon('chevron-left', 'Back', class: 'fa-fw'), incident_types_path %>
    </div>
    <div class="pull-right">
      <%= link_to 'Show', @incident_type %>
    </div>
  </div>
  <div class="row col-sm-12">
  <h1 class="text-center">Editing Incident Type</h1>
  </div>
  <%= render 'form' %>
</div>

app/views/incident_types/index.html.erb
<div class="container spaced">
  <div class="row">
    <div class="col-sm-12">
      <div class="pull-right">
        <% if current_user %>
        <%= link_to icon('plus', 'New Incident Type', class: 'fa-fw'), new_incident_type_path %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <%= render 'layouts/notice', notice: notice %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <h1 class="text-center">Listing Incident Types</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Name</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @incident_types.each do |incident_type| %>
            <tr>
              <td><%= incident_type.name %></td>
              <td><%= link_to icon('eye'), incident_type, class: 'text-info' %></td>
              <% if current_user %>
              <td><%= link_to icon('pencil'), edit_incident_type_path(incident_type), class: 'text-muted' %></td>
              <td><%= link_to icon('times'), incident_type, method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-danger' %></td>
              <% end %>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <%= paginate @incident_types %>
    </div>
  </div>
</div>

app/views/incident_types/new.html.erb
<div class="container spaced">
  <div class="row col-sm-12">
    <div class="pull-left">
      <%= link_to icon('chevron-left', 'Back', class: 'fa-fw'), incident_types_path %>
    </div>
    <div class="pull-right">

    </div>
  </div>
  <div class="row col-sm-12">
  <h1 class="text-center">New Incident Type</h1>
  </div>
  <%= render 'form' %>
</div>

app/views/incident_types/show.html.erb
<div class="container spaced">
  <div class="row">
    <div class="col-sm-12">
      <div class="pull-left">
        <%= link_to icon('chevron-left', 'Back', class: 'fa-fw'), incident_types_path %>
      </div>
      <div class="pull-right">
        <% if current_user %>
        <%= link_to icon('pencil', 'Edit', class: 'fa-fw'), edit_incident_type_path(@incident_type) %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row col-sm-12">
    <%= render 'layouts/notice', notice: notice %>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <h1 class="text-center">Incidents of <%= @incident_type.name %></h1>
    </div>
  </div>
  <% if @incident_type.incidents.empty? %>
  <div class="row">
    <div class="col-sm-12">
      <p class="lead text-center text-muted">No incidents of this type reported yet.</p>
    </div>
  </div>
  <% else %>
  <div class="row">
    <div class="col-sm-12">
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>When</th>
              <th>Action Taken</th>
              <th>Location</th>
              <th>Open ?</th>
              <th>Reporter</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @incidents.each do |incident| %>
            <tr>
              <td><%= date_time incident.created_at %></td>
              <td><%= incident.action_taken %></td>
              <td><%= incident.location %></td>
              <td>
                <% if incident.open %>
                <%= icon('check', '', class: 'text-danger') %>
                <% else %>
                <%= icon('times', '', class: 'text-success') %>
                <% end %>
              </td>
              <td><%= incident.user.name %></td>
              <td><%= link_to icon('eye'), incident, class: 'text-info' %></td>
              <% if current_user %>
              <td><%= link_to icon('pencil'), edit_incident_path(incident), class: 'text-muted' %></td>
              <td><%= link_to icon('times'), incident, method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-danger' %></td>
              <% end %>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <% end %>
  <div class="row">
    <div class="col-md-12">
      <%= paginate @incidents %>
    </div>
  </div>
</div>