config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  resources :roles
  get '/' => 'home#index', as: :root_path

  resources :severity_levels
  resources :incident_types
  resources :fires
  resources :incidents
  devise_for :users, controllers: { registrations: 'registrations' }
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= image_tag 'bonfire.svg', height: 35, class: 'header-logo' %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Fires<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if current_user %>
            <li><%= link_to icon('plus', 'Report New', class: 'fa-fw'), new_fire_path %></li>
            <% end %>
            <li><%= link_to icon('eye', 'Reported Fires', class: 'fa-fw'), fires_path %></li>
            <li><%= link_to icon('fire-extinguisher', 'Severity Levels', class: 'fa-fw'), severity_levels_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Incidents <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if current_user %>
            <li><%= link_to icon('plus', 'Report New', class: 'fa-fw'), new_incident_path %></li>
            <% end %>
            <li><%= link_to icon('eye', 'Reported Incidents', class: 'fa-fw'), incidents_path %></li>
            <li><%= link_to icon('tag', 'Incident Types', class: 'fa-fw'), incident_types_path %></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
        <% if current_user_is 'master' %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
           aria-haspopup="true" aria-expanded="false"><i class="fa fa-cog"></i> Manage <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to icon('users','Roles', class: 'fa-fw'), roles_path %></li>
          </ul>
        </li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
           aria-haspopup="true" aria-expanded="false"><%= current_user.name %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to icon('pencil', 'Edit Account', class: 'fa-fw'), edit_user_registration_path(current_user) %></li>
            <li class="divider"></li>

            <li><%= link_to(icon('sign-out', 'Sign Out', class: 'fa-fw'), destroy_user_session_path, method: :delete) %></li>
          </ul>
        </li>
        <% else %>
        <li>
          <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_notice.html.erb
<% if notice %>
<div class="spaced">
  <div class="alert alert-info alert-dismissible fade in" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <span><%= notice %> </span>
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fireplace</title>
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
  <meta name="theme-color" content="#F99C38">
  <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
  <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
  <link rel="manifest" href="/manifest.json">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="//maps.google.com/maps/api/js?v=3.23&key=<%=ENV['FIREPLACE_MAPS_KEY']%>"></script>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <%= yield %>

</body>
</html>